### ISSUE TITLE
Sling channels not playing

### ISSUE THREAD

**Issue by bds3151** [Lunatixz/plugin.video.slingtv#9]
When I click on any channel in the Kodi 18.3 Sling Tv add on, I get the dashed circles rotating and then it doesn't start playback. When I look at the log, it says "InputStream Adaptive license update not successful- no keys". I have 3 win10 machines that started this issue today.

**Comment by eracknaphobia** [comment]
I'm seeing the same issue on my end. I will look into this further and see what can be done to fix it.

**Comment by bds3151** [comment]
Thanks for your help.

**Comment by eracknaphobia** [comment]
Seems the issue is related to inputstream helper not getting the latest version of widevine.  https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/59

Until the PR is pulled into inputstream helper the manually fix can be found here:
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/60

**Comment by bds3151** [comment]
Sorry but could you please explain how to implement the manual fix? I read the link but didn't understand how this fixed the issue before the PR is implemented.

**Comment by eracknaphobia** [comment]
@bds3151 The fix PR has been pulled in and inputstreamhelper has been updated. Kodi should auto update now.

**Comment by bds3151** [comment]
Thanks again for your help eracknaphobia.
